services:
  - type: web
    name: kaelon-api
    runtime: node
    plan: free
    buildCommand: npm install && npx prisma generate
    startCommand: npx prisma migrate deploy && node server/src/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: CLIENT_URL
        value: https://pc-build-delta.vercel.app
      - key: COOKIE_SECURE
        value: "true"
      - key: COOKIE_SAMESITE
        value: none
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: ADMIN_EMAIL
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
